project:
  type: website

website:
  title: "Marshall Electrochemical Engineering Lab"

  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Research
      - href: publications.qmd
        text: Publications
      - href: members.qmd
        text: Members
      - href: posts.qmd
        text: News

  page-footer:
    left: "Marshall Electrochemical Engineering Lab"
    right: "Built with Quarto"

format:
  html:
    theme: cosmo
    toc: true