project:
  type: website
  output-dir: _site

website:
  title: "Marshall Electrochemical Engineering Lab"
  site-url: https://marshall-echem-lab.github.io/research/

  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Research
      - href: publications.qmd
        text: Publications
      - href: members.qmd
        text: Members
      - href: posts.qmd
        text: Posts
      - href: news.qmd
        text: News

  page-footer:
    left: "Marshall Electrochemical Engineering Lab"
    right: "Built with Quarto"

format:
  html:
    theme: cosmo
    toc: false